spring:
  application:
    name: Java Trainee Tech Task
server:
  port: 9080

logging:
  level:
    org: info
    com: off

---

spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:data
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  logging:
    level:
      org: info
      com: off

---

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

---

spring:
  jpa:
    hibernate:
      ddl-auto: update

